#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build: 
    context: .  
    dockerfile: Dockerfile
  image: pomelo925/discord-bot:TeAsis

  volumes:
    # workspace 
    - ../discord-bot:/discord-bot

  env_file:
    - config/dcbot.token.env

  environment:
    - DISPLAY=${DISPLAY}

  tty: true
  network_mode: host
  privileged: true
  stop_grace_period: 1s


##############################
###   Container Services   ###
##############################
services:
  default:
    <<: [*common]  
    container_name: deploy
    labels:
      - "com.centurylinklabs.watchtower.scope=pomelo925"
    command: ["python", "bot.py"]

  dev:
      <<: [*common]
      container_name: dev
      labels:
        - "com.centurylinklabs.watchtower.scope=pomelo925"
      command: ["tail", "-f", "/dev/null"]